name: Test and Deploy

#on:
  #workflow_run:
    #workflows: [ "e2e-tests" ]
    #types: [ completed ]
    
#on:
  #pull_request:
    #branches: [ main ]
    
#on:
  #release:
    #types: [ published ]
    
on: [ workflow_dispatch ]

jobs:

  xunit:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: run-tests
        run: |
        echo "${{ secrets.ENV_FILE }}" > ./AdministrationAPI/.env.prod
        dotnet restore
        dotnet test
    

  deploy:
    needs: xunit

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Setup .env.prod file
      run: |
        echo "${{ secrets.ENV_FILE }}" > ./AdministrationAPI/.env.prod

    - name: Build the backend image
      run: docker build . --file ./AdministrationAPI/Dockerfile.prod --tag evlahovlja1/siprojekat-backend:$(date +%s) --tag evlahovlja1/siprojekat-backend:latest
      
    - name: Docker Push backend
      run: docker push evlahovlja1/siprojekat-backend --all-tags